INSERT INTO companies (
        company_name, valuation_usd, crunchbase_total_investment_usd,
        markets, days_since_last_fundraise, linkedin_headcount,
        linkedin_headcount_mom_percent, linkedin_headcount_qoq_percent,
        linkedin_headcount_yoy_percent, linkedin_headcount_mom_absolute,
        linkedin_headcount_qoq_absolute, linkedin_headcount_yoy_absolute,
        glassdoor_overall_rating, glassdoor_ceo_approval_pct,
        glassdoor_business_outlook_pct, glassdoor_review_count,
        g2_review_count, g2_average_rating, hq_country,
        largest_headcount_country, last_funding_round_type,
        company_website, company_website_domain, valuation_date,
        linkedin_categories, linkedin_industries, crunchbase_investors,
        crunchbase_categories, linkedin_profile_url, acquisition_status,
        company_year_founded, technology_domains, founder_names_and_profile_urls,
        founders_location, founders_education_institute, founders_degree_name,
        founders_previous_company, founders_previous_title, monthly_visitors,
        monthly_visitor_mom_pct, traffic_source_social_pct,
        traffic_source_search_pct, traffic_source_direct_pct,
        traffic_source_paid_referral_pct, traffic_source_referral_pct,
        meta_total_ads, meta_active_ads, meta_ad_platforms,
        meta_ad_url, meta_ad_id, average_organic_rank,
        monthly_paid_clicks, monthly_organic_clicks, average_ad_rank,
        total_organic_results, monthly_google_ads_budget,
        monthly_organic_value, total_ads_purchased, lost_ranks,
        gained_ranks, newly_ranked, paid_competitors, organic_competitors,
        linkedin_id, linkedin_followers, linkedin_headcount_engineering,
        linkedin_headcount_sales, linkedin_headcount_operations,
        linkedin_headcount_human_resource, linkedin_headcount_india,
        linkedin_headcount_usa, linkedin_headcount_engineering_percent,
        linkedin_headcount_sales_percent, linkedin_headcount_operations_percent,
        linkedin_headcount_human_resource_percent, linkedin_headcount_india_percent,
        linkedin_headcount_usa_percent, linkedin_followers_mom_percent,
        linkedin_followers_qoq_percent, linkedin_followers_yoy_percent,
        glassdoor_culture_rating, glassdoor_diversity_rating,
        glassdoor_work_life_balance_rating, glassdoor_senior_management_rating,
        glassdoor_compensation_rating, glassdoor_career_opportunities_rating,
        glassdoor_recommend_to_friend_pct, glassdoor_ceo_approval_mom_pct,
        glassdoor_ceo_approval_qoq_pct, glassdoor_review_count_mom_pct,
        glassdoor_review_count_qoq_pct, glassdoor_review_count_yoy_pct,
        g2_review_count_mom_pct, g2_review_count_qoq_pct,
        g2_review_count_yoy_pct, instagram_followers, instagram_posts,
        instagram_followers_mom_pct, instagram_followers_qoq_pct,
        instagram_followers_yoy_pct, recent_job_openings_title,
        recent_job_openings_title_count, job_openings_count,
        job_openings_count_mom_pct, job_openings_count_qoq_pct,
        job_openings_count_yoy_pct, job_openings_accounting_qoq_pct,
        job_openings_accounting_six_months_growth_pct, job_openings_art_and_design_qoq_pct,
        job_openings_art_and_design_six_months_growth_pct,
        job_openings_business_development_qoq_pct,
        job_openings_business_development_six_months_growth_pct,
        job_openings_engineering_qoq_pct, job_openings_engineering_six_months_growth_pct,
        job_openings_finance_qoq_pct, job_openings_finance_six_months_growth_pct,
        job_openings_human_resource_qoq_pct,
        job_openings_human_resource_six_months_growth_pct,
        job_openings_information_technology_qoq_pct,
        job_openings_information_technology_six_months_growth_pct,
        job_openings_marketing_qoq_pct, job_openings_marketing_six_months_growth_pct,
        job_openings_media_and_communication_qoq_pct,
        job_openings_media_and_communication_six_months_growth_pct,
        job_openings_operations_qoq_pct, job_openings_operations_six_months_growth_pct,
        job_openings_research_qoq_pct, job_openings_research_six_months_growth_pct,
        job_openings_sales_qoq_pct, job_openings_sales_six_months_growth_pct,
        job_openings_product_management_qoq_pct,
        job_openings_product_management_six_months_growth_pct,
        job_openings_overall_qoq_pct, job_openings_overall_six_months_growth_pct,
        total_rows
    )
    VALUES (
        %s, %s, %s::float, %s, %s::int, %s::int,
        %s::float, %s::float, %s::float, %s::int, %s::int,
        %s::int, %s::float, %s::float, %s::float, %s::int, %s::int,
        %s::float, %s, %s, %s, %s, %s, %s::date, %s, %s, %s, %s,
        %s, %s, %s, %s, %s, %s, %s, %s, %s::float, %s::float,
        %s::float, %s::float, %s::float, %s::float, %s::float,
        %s::float, %s::float, %s::int, %s::int, %s::int, %s, %s,
        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::float, %s::float,
        %s::float, %s, %s, %s, %s::float, %s::float, %s::float,
        %s::float, %s::float, %s::float, %s::float, %s::float, %s,
        %s, %s, %s::float, %s::float, %s::float, %s::float, %s::float,
        %s::float, %s::float, %s, %s::int, %s::int, %s::int,
        %s::float, %s::float, %s::float, %s::float, %s::float, %s::float,
        %s::float, %s::float, %s::float, %s::float, %s::float, %s,
        %s, %s, %s, %s, %s, %s, %s::float, %s::float, %s::float,
        %s::float, %s::float, %s::float, %s::float, %s::float, %s::float,
        %s, %s::float, %s::float, %s::float, %s::float, %s::float, %s,
        %s, %s, %s, %s, %s, %s, %s, %s, %s
    );